### ISSUE TITLE
I always get 'Cannot resolve route for link param...'

### ISSUE THREAD

**Issue by MikeMitterer** [angel-dart/route#23]
Hi, my config looks like this:

```dart
main() {
    ...
    final router = new BrowserRouter(hash: true);
    _configRouter(router);
   ...
}

void _configRouter(final BrowserRouter router ) {
    configLogging(show: Level.INFO);
    
    final Logger _logger = new Logger('main.configRouter');

    router.onResolve.listen((result) {
        final route = result?.route;
        if (route == null) {
            _logger.shout('No Active Route');
        } else {
            _logger.shout('Active Route: ${route.name ?? route.path}');
        }
    });
    
    router.get("/test", () {
        print("/Test.html");
        
        _logger.info("/Test.html");
    });

    router.get("test", () {
        print("Test.html");

        _logger.info("Test.html");
    });

    router.get("/#/test2", () {
        _logger.info("Test2.html");
    });

    router..dumpTree()..listen(); // Start listening
}
```
My links
```html
<a href="/test">Test</a> | <a href="/#/test2">Test II</a>
```
But I geht either `Cannot resolve route for link param "test"` for the first link or `Cannot resolve route for link param "#"` for the second link

Any ideas?

**Comment by thosakwe** [comment]
The hashmark (#) shouldn’t be included in your router configuration.

The router doesn’t use that when resolving, as the hash ultimately gets stripped away.

Just use `router.get(‘/test2’, ...)`.

As an added note, the “/test” and “test” routes are equivalent, as the leading path is stripped out. They will both match the exact same paths.

**Comment by thosakwe** [comment]
Also, the BrowserRouter will listen to either onHashChange or pushState, but not both simultaneously.
